openldap:
  fullnameOverride: ldap-openldap
  enabled: true
  adminPassword: ''
  env:
    LDAP_BASE_DN: dc=example,dc=org
  customLdifFiles:
    init.ldif : |
      dn: ou=orgs,dc=example,dc=org
      objectClass: top
      objectClass: organizationalUnit
      ou: orgs
andi:
  enabled: true
  redis:
    host: ''
    password: ''

  strimzi:
    kafka:
      brokers: streaming-service-kafka-bootstrap:9092
  service:
    type: ClusterIP
discovery-api:
  redis:
    host: ''
    password: ''
  presto:
    url: http://platform-kubernetes-data-platform-presto:8080
  postgres:
    host: ''
    dbname: ''
    user: ''
  kafka:
    brokers: streaming-service-kafka-bootstrap:9092
  s3:
    hostedFileBucket: hosted-bucket
  ldap:
    host: ldap-openldap
    base: "dc=example,dc=org"
  vault:
    endpoint: ""
  environment: demo
  service:
    type: LoadBalancer
discovery-streams:
  enabled: false
  image:
    environment: demo
    tag: 0.12.4
  service:
    type: LoadBalancer
kubernetes-data-platform:
  fullnameOverride: kdp
  enabled: false
  global:
    environment: demo
    objectStore:
      bucketName: ''
      accessKey: ''
      accessSecret: ''
    ingress:
      annotations: {}
  presto:
    workers: 2
    ingress:
      enable: false
      annotations: {}
    jvm:
      maxHeapSize: 1536M
    deploy:
      container:
        resources:
          limits:
            memory: 2Gi
            cpu: 2
          requests:
            memory: 2Gi
            cpu: 1
  minio:
    enable: true
    gateway:
      enable: false
      type: azure
    googleCredentials:
      project_id: ''
      private_key_id: ''
      private_key: ''
      client_email: ''
      client_id: ''
      client_x509_cert_url: ''
  postgres:
    enable: true
    service:
      externalAddress: ''
    db:
      name: metastore
      user: ''
      password: ''
  metastore:
    allowDropTable: true
    timeout: 360m
forklift:
  fullnameOverride: forklift
  enabled: true
  kafka:
    brokers: streaming-service-kafka-bootstrap:9092
  kdp:
    url: "http://platform-kubernetes-data-platform-presto:8080"
  redis:
    host: ''
    password: ''
  prometheus:
    scrape: false
reaper:
  fullnameOverride: reaper
  enabled: true
  redis:
    host: ''
    password: ''
  strimzi:
    kafka:
      brokers: streaming-service-kafka-bootstrap:9092
  vault:
    endpoint: ""
valkyrie:
  fullnameOverride: valkyrie
  enabled: true
  replicaCount: 1
  kafka:
    brokers: streaming-service-kafka-bootstrap:9092
  redis:
    host: ''
    password: ''
flair:
  enabled: false
  redis:
    host: redis-master
  strimzi:
    kafka:
      brokers: streaming-service-kafka-bootstrap:9092
odo:
  enabled: true
kafka:
  enabled: true
  storage:
    enable: false
    storageSize: 5Gi
redis:
  enabled: false
