{{- if .Values.openldap.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ldap
type: Opaque
data:
  host: bGRhcC1vcGVubGRhcA== # ldap-openldap
  base_dn: ZGM9ZXhhbXBsZSxkYz1vcmc= # dc=example,dc=org
  user: Y249YWRtaW4= # cn=admin
  password: YWRtaW4= #admin
  environment_ou: b3Jncw== # orgs
{{- end }}