---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: streaming-dead-letters
  labels:
    strimzi.io/cluster: {{ .Values.kafka.strimziCluster }}
spec:
  partitions: 1
  replicas: 1
  config: {}
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: event-stream
  labels:
    strimzi.io/cluster: {{ .Values.kafka.strimziCluster }}
spec:
  partitions: 1
  replicas: 1
  config: {}
