apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: reaper-autoscaler
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reaper
  targetCPUUtilizationPercentage: 80